version: '3.8'
services:
  mongo:
    image: mongo:4.4.2-bionic
    restart: always
    ports:
      - $DB_HOST:$DB_PORT:27017
    volumes:
      - ./tmp/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
      MONGO_INITDB_DATABASE: $DB_NAME
